# Generated by Django 5.0.1 on 2024-01-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField()),
                ('total', models.FloatField(default=0)),
                ('shipping_type', models.CharField(default='SELF_PICKUP', max_length=50)),
                ('shipping_cost', models.FloatField(default=0)),
                ('vat_amount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('invoice_id', models.CharField(default='0000000', max_length=7)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
                ('payment_method', models.CharField(default='Cash on Delivery', max_length=50)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'order',
            },
        ),
    ]
